better_login.config:
  path: '/admin/config/user-interface/better-login-form'
  defaults:
    _form: '\Drupal\better_login_form_config\Form\BettrLoginConfigForm'
    _title: 'Better login form Configuration'
  requirements:
    _permission: 'administer site configuration'
