name: Bamboo Twig - Config
description: 'Several "Config" Twig extensions.'
package: Bamboo Twig
type: module
core_version_requirement: ^8.8 || ^9

dependencies:
 - bamboo_twig:bamboo_twig

# Information added by Drupal.org packaging script on 2020-01-10
version: '8.x-5.0-alpha1'
project: 'bamboo_twig'
datestamp: 1578674587
