<?php

/**
 * Implements hook_theme().
 */
function external_media_theme() {
  return [
    'external_media' => [
      'variables' => ['label' => NULL, 'class' => NULL, 'attributes' => []],
    ],
    'external_media_element' => ['render element' => 'element'],
  ];
}

/**
 * Preprocess function for the external-media.html.twig template.
 */
function external_media_preprocess_external_media(&$variables) {
  if (!empty($variables['attributes'])) {
    $attributes = [];
    foreach ($variables['attributes'] as $data => $value) {
      $attributes[] = ' data-' . $data . '="' . $value . '"';
    }
    $variables['data_attributes'] = join(' ', $attributes);
  }
}

/**
 * Implements hook_library_info_build().
 */
function external_media_library_info_build() {
  $libraries = [];
  $external_media = \Drupal::service('plugin.manager.external_media');
  foreach ($external_media->getDefinitions() as $plugin) {
    $plugin = $external_media->createInstance($plugin['id']);
    if ($plugin->classExists() && $plugin->getModule() == 'external_media') {
      $libraries[$plugin->getModule() . '.' . $plugin->getPluginId()] = $plugin->getLibraries();
    }
  }
  return $libraries;
}

/**
 * Implements hook_preprocess_form_element().
 */
function external_media_preprocess_form_element(&$variables) {
  if ($variables['type'] == 'external_media') {
    $variables['attributes']['class'][] = 'form-type-external-media';
  }
}
